<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>txt</string>
		<string>ios</string>
	</array>
	<key>name</key>
	<string>Cisco</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Cryptography</string>
			<key>match</key>
			<string>crypto </string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Highlight comments</string>
			<key>match</key>
			<string>^[\s]*!(.*)</string>
			<key>name</key>
			<string>comment.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Highlight Stars</string>
			<key>match</key>
			<string>\*</string>
			<key>name</key>
			<string>comment.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Highlight quotes</string>
			<key>match</key>
			<string>\"</string>
			<key>name</key>
			<string>comment.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tunnel group</string>
			<key>match</key>
			<string>tunnel-group</string>
			<key>name</key>
			<string>support.class.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Service</string>
			<key>match</key>
			<string>(?&lt;=\s|^)service</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Cryptography</string>
			<key>match</key>
			<string>crypto</string>
			<key>name</key>
			<string>support.class.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Access List</string>
			<key>match</key>
			<string>access-list</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Username Config(s)</string>
			<key>match</key>
			<string>username</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Authentication Providers</string>
			<key>match</key>
			<string>aaa</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Time service setting</string>
			<key>match</key>
			<string>clock</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>system service setting</string>
			<key>match</key>
			<string>system</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>routing service setting</string>
			<key>match</key>
			<string>routing</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>IP Service settings</string>
			<key>match</key>
			<string>(?&lt;=\s|^)ip</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Spanning Tree settings</string>
			<key>match</key>
			<string>spanning-tree</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>VTP settings</string>
			<key>match</key>
			<string>vtp</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Error Disable settings</string>
			<key>match</key>
			<string>errdisable</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Interface config settings</string>
			<key>match</key>
			<string>interface</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SNMP config settings</string>
			<key>match</key>
			<string>snmp-server</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>SNMP config settings</string>
			<key>match</key>
			<string>banner</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line config settings</string>
			<key>match</key>
			<string>line\s(con|vty)</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Switchport settings</string>
			<key>match</key>
			<string>switchport</string>
			<key>name</key>
			<string>support.function.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hostname</string>
			<key>match</key>
			<string>hostname</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>incoming</string>
			<key>match</key>
			<string>incoming</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>password</string>
			<key>match</key>
			<string>password</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>exec-timeout</string>
			<key>match</key>
			<string>exec-timeout</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>access-class</string>
			<key>match</key>
			<string>access-class</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>transport</string>
			<key>match</key>
			<string>transport</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>notify</string>
			<key>match</key>
			<string>notify</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Enable Password</string>
			<key>match</key>
			<string>enable</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Logging options</string>
			<key>match</key>
			<string>logging</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>VLAN Handling</string>
			<key>match</key>
			<string>vlan</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Port Channel options</string>
			<key>match</key>
			<string>port-channel</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Radius options</string>
			<key>match</key>
			<string>radius-server</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>NTP Server options</string>
			<key>match</key>
			<string>ntp server</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Interface Description options</string>
			<key>match</key>
			<string>description</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>deny access list</string>
			<key>match</key>
			<string>deny </string>
			<key>name</key>
			<string>support.constant.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>permit access list</string>
			<key>match</key>
			<string>permit </string>
			<key>name</key>
			<string>support.constant.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>static</string>
			<key>match</key>
			<string>static</string>
			<key>name</key>
			<string>constant.numeric.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Highlight numbers</string>
			<key>match</key>
			<string>\d+\.\d+\.\d+\.\d+(/\d{1,2})?</string>
			<key>name</key>
			<string>constant.numeric.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Highlight IP numbers</string>
			<key>match</key>
			<string>[0-9a-fA-F]{0,4}:([0-9a-fA-F]{0,4}:)+[0-9a-fA-F]{0,4}(/\d{1,3})?</string>
			<key>name</key>
			<string>constant.numeric.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Highlight numbers</string>
			<key>match</key>
			<string>\d+(=?(\s|$))</string>
			<key>name</key>
			<string>constant.numeric.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ANY mostly used for access lists</string>
			<key>match</key>
			<string>any</string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>http</string>
			<key>match</key>
			<string>http</string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>udp</string>
			<key>match</key>
			<string>udp</string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tcp</string>
			<key>match</key>
			<string>tcp</string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cause</string>
			<key>match</key>
			<string>cause</string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>interval</string>
			<key>match</key>
			<string>interval</string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>range</string>
			<key>match</key>
			<string>range</string>
			<key>name</key>
			<string>string.unquoted.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>recovery</string>
			<key>match</key>
			<string>recovery</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>forward-protocol</string>
			<key>match</key>
			<string>forward-protocol</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>privilege</string>
			<key>match</key>
			<string>privilege</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>secret</string>
			<key>match</key>
			<string>secret</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>classless</string>
			<key>match</key>
			<string>classless</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>community</string>
			<key>match</key>
			<string>community</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>address</string>
			<key>match</key>
			<string>address</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>authentication</string>
			<key>match</key>
			<string>authentication</string>
			<key>name</key>
			<string>variable.parameter.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Default command</string>
			<key>match</key>
			<string>^\s*default </string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Negate command</string>
			<key>match</key>
			<string>^\s*no(=?\s)</string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Shudown an interface</string>
			<key>match</key>
			<string>shutdown</string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>exit</string>
			<key>match</key>
			<string>exit</string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>end</string>
			<key>match</key>
			<string>^end</string>
			<key>name</key>
			<string>invalid.illegal.cisco</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.cisco</string>
	<key>uuid</key>
	<string>65b8e7fa-d84d-4416-9913-be7bae0211bd</string>
</dict>
</plist>
